### ISSUE TITLE
PrepareAnvilEvent on minecraft 1.20.x

### ISSUE THREAD

**Issue by BagroSlave** [qu4ks/Autograph#1]
I can't use anvil to sign item on my server (minecraft 1.20.2).
Here is console log:
```
[Server thread/ERROR]: Could not pass event PrepareAnvilEvent to Autograph v1.2.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1609) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.ContainerAnvil.m(ContainerAnvil.java:168) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:112) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.ContainerAnvilAbstract$3.e(ContainerAnvilAbstract.java:103) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.Slot.d(SourceFile:80) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.Slot.e(SourceFile:76) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.Slot.a(SourceFile:66) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.Slot.d(SourceFile:63) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.Container.a(Container.java:827) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:158) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.Container.b(Container.java:532) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.world.inventory.Container.a(Container.java:376) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2666) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:32) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1133) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1112) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1105) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1089) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3925-Spigot-dba3cdc-5a72c3c]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "by.quaks.autograph.Utils.getItemName(org.bukkit.inventory.ItemStack)" is null
	at by.quaks.autograph.AnvilCraft.onPrepareAnvil(AnvilCraft.java:35) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	... 32 more

```

**Comment by egorquaks** [comment]
Plugin is paper-only
